addresses feedback on ap-2211, 2212, and 2106
looker/viz-multiple_value-marketplace pull request #11
Opened 2020-09-03 05:36 UTC by noahamac

https://looker.atlassian.net/browse/AP-2106
https://looker.atlassian.net/browse/AP-2212
https://looker.atlassian.net/browse/AP-2211

Would appreciate help testing this, too. Dev variant is ready to go on app.dev. Try to take this PR through the ringer... Whatever edge cases you can think of while testing, and whatever nits you have about the code. 

Thanks so much!

2020-09-03 17:33 UTC, thomasbanghart requested changes
Correct me if I'm wrong, but at least when I tried to build this PR locally, those ts errors prevented the build so the dist file didn't update as expected. Maybe ts-ignore will suffice on those lines for now? 

Otherwise, everything looks great and addresses the FRs! 👍 Also resolves the issues we saw on db-next. Nice!

2020-09-03 17:33 UTC, thomasbanghart commented on multiple_value.js
> + */var r="function"==typeof Symbol&&Symbol.for,i=r?Symbol.for("react.element"):60103,o=r?Symbol.for("react.portal"):60106,a=r?Symbol.for("react.fragment"):60107,u=r?Symbol.for("react.strict_mode"):60
I think this dist file is missing the feature updates -- no biggie if we make sure the CDN version has it but might be a good idea to make sure what is here matches what we have on the CDN

2020-09-03 17:33 UTC, thomasbanghart commented on src/multiple_value/ComparisonDataPoint.tsx
> +      <ComparisonPercentageChange value={percChange} onClick={() => { handleClick(compDataPoint, event) }}>
resolve ts errors, no ts-ignore

2020-09-03 17:33 UTC, thomasbanghart commented on src/multiple_value/ComparisonDataPoint.tsx
> +        {percChange >= 0 ? <UpArrow pos={config[`pos_is_bad_${compDataPoint.name}`]}/> : <DownArrow pos={config[`pos_is_bad_${compDataPoint.name}`]}/>}
resolve ts errors, no ts-ignore

2020-09-03 17:33 UTC, thomasbanghart commented on src/multiple_value/ComparisonDataPoint.tsx
> +          background={config[`style_${dataPoint.name}`]}
resolve ts errors, no ts-ignore

2020-09-03 17:33 UTC, thomasbanghart commented on src/multiple_value/multiple_value_container.js
> +  },
🙇

2020-09-03 17:33 UTC, thomasbanghart commented on src/multiple_value/multiple_value_container.js
> +      if (config.orientation === "horizontal") {
Love the conditional options and the dividers look really nice 👍

2020-09-08 18:01 UTC, noahamac commented on webpack.config.js
> +    headers: {
Yes :pray:

2020-09-08 19:15 UTC, noahamac commented on multiple_value.js
> + */var r="function"==typeof Symbol&&Symbol.for,i=r?Symbol.for("react.element"):60103,o=r?Symbol.for("react.portal"):60106,a=r?Symbol.for("react.fragment"):60107,u=r?Symbol.for("react.strict_mode"):60
Good catch

2020-09-08 21:47 UTC, noahamac commented on src/multiple_value/multiple_value_container.js
> +      if (config.orientation === "horizontal") {
I actually changed the implementation away from borders and into self contained components... Let me know what u think of that

2020-09-08 22:28 UTC, noahamac commented
Ok, cleaned some things up. Got rid of my ts-ignores :shudder:. You can find the viz on mp-viz: https://app.dev.looker.com/dashboards/710

Would appreciate another front-end test and code review @thomasbanghart

2020-09-08 23:10 UTC, thomasbanghart commented
Awesome 👏  Thanks so much Noah!!

2020-09-08 23:10 UTC, merged

2020-09-08 23:13 UTC, thomasbanghart reviewed
LGTM!

2020-09-08 23:13 UTC, thomasbanghart commented on src/multiple_value/ComparisonDataPoint.tsx
> +  function tryFormatting(formatString: string, value: number, defaultString: string) {
Nice 👍

2021-02-01 20:18 UTC, jcbmllgn commented
Thanks for the continued work & maintenance of this package 🙌 🙇