AP-2318: Sets default font size and orientation for db-next
looker/viz-multiple_value-marketplace pull request #17
Opened 2020-11-06 22:45 UTC by thomasbanghart

Ticket: https://looker.atlassian.net/browse/AP-2318

Adds checks for undefined config elements to better support default settings on db-next. Let me know if this works for the time being!

2020-11-06 23:40 UTC, noahamac requested changes

2020-11-06 23:40 UTC, noahamac commented on src/multiple_value/multiple_value.js
> +        layout={config['orientation'] === 'auto' || typeof config['orientation'] === 'undefined' ? this.state.groupingLayout : config['orientation']}
I know I'm guilty of this too, but let's factor this out into a helper function without the ternary. For all 3 uses, `getLayout()`

2020-11-06 23:41 UTC, thomasbanghart commented on src/multiple_value/multiple_value.js
> +        layout={config['orientation'] === 'auto' || typeof config['orientation'] === 'undefined' ? this.state.groupingLayout : config['orientation']}
100% agree, it'll definitely help with readability

2020-11-07 00:36 UTC, noahamac approved these changes

2020-11-08 22:39 UTC, merged